vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        cow_images:
            uri_prefix: /images/cow
            upload_destination: '%kernel.project_dir%/public/images/cow'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
