vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        cows:
            uri_prefix: /images/cows
            upload_destination: '%kernel.project_dir%/public/images/cows'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
